const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'

export {
  PRODUCT_LIST_REQUEST,
  PRODUCT_LIST_SUCCESS,
  PRODUCT_LIST_FAIL,
  PRODUCT_DETAILS_REQUEST,
  PRODUCT_DETAILS_SUCCESS,
  PRODUCT_DETAILS_FAIL,
  PRODUCT_DELETE_REQUEST,
  PRODUCT_DELETE_SUCCESS,
  PRODUCT_DELETE_FAIL,
  PRODUCT_CREATE_REQUEST,
  PRODUCT_CREATE_SUCCESS,
  PRODUCT_CREATE_FAIL,
  PRODUCT_CREATE_RESET,
  PRODUCT_UPDATE_REQUEST,
  PRODUCT_UPDATE_SUCCESS,
  PRODUCT_UPDATE_FAIL,
  PRODUCT_UPDATE_RESET,
  PRODUCT_CREATE_REVIEW_REQUEST,
  PRODUCT_CREATE_REVIEW_SUCCESS,
  PRODUCT_CREATE_REVIEW_FAIL,
  PRODUCT_CREATE_REVIEW_RESET,
  PRODUCT_TOP_REQUEST,
  PRODUCT_TOP_SUCCESS,
  PRODUCT_TOP_FAIL,
}
